version: "3.5"

services:
  db:
    image: mysql
    container_name: tech-challenge-db
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fastfood
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: tech-challenge-api
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=fastfood
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db: