services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    container_name: mongo
    image: mongo:7.0.3
    restart: always
    ports:
      - "27017:27017"