openapi: 3.0.3
info:
  title: Swagger Lanchonete - 9SOAT
  description: |-
    Aplicação para gerenciamento de pedidos
    
    Turma 9SOAT
  version: 1.0.0
externalDocs:
  description: Repositório
  url: https://github.com/matheustrindade/lanchonete-9soat-fase1
tags:
  - name: healthy
    description: rota para verificação de estado da aplicação
paths:
  /healthy:
    get:
      tags:
        - healthy
      summary: Verifica estado da aplicação
      responses:
        '200':
          description: sucesso
        '500':
          description: erro